### ISSUE TITLE
corrupted file loading handling

### ISSUE THREAD

**Issue by pmp-p** [IndiePython/nodezator#18]
https://github.com/KennedyRichard/nodezator/blob/db450b84f439f3b458b4c0c80dcfed47432bfe03/nodezator/ourstdlibs/pyl.py#L18 is not catching SyntaxError on malformed file. It would be helpful to at least display an error and full pathname of faulty document.

sidenote: on retry after a crash the full pathname is not displayed either.

**Comment by KennedyRichard** [comment]
You are right, unexpected errors should be gently caught and reported. Thank you for the report. I'll fix this after handling the more urgent issue #19 (since it is related to a more essential feature) and after pushing and merging the resizable-window branch to make Nodezator window resizable, which should take me 02 to 03 days, give or take.

**Comment by KennedyRichard** [comment]
Hello, Mr. Peny,

The issue was solved and the fixed version already uploaded to pypi. Thank you for your patience.

I apologize for the delay. Even though my reasons to postpone solving this issue were legitimate (I had to work on more pressing/urgent scheduled tasks for this project), I should have reported back to you sooner about it, rather than leaving you hanging for so much time.

Thank you again for having taken the time to report. I'll strive to be more frequent in updating people about my work.

Since I finished my scheduled tasks and solved this issue, I should now be able to tackle your pull requests.
