### ISSUE TITLE
Classes with inheritance as main_callable will be called with the parent __init__, not the overriden one.

### ISSUE THREAD

**Issue by gregismotion** [IndiePython/nodezator#94]
Node:
```python
from lazysocials.platforms import Twitter
from lazysocials.platforms.twitter import TwitterAuth

from lazycommon.content.types import Content

from typing import Type

main_callable = Twitter

def _Twitter(auth: TwitterAuth, max_images: {"widget_name": "int_float_entry", "widget_kwargs": {"min_value": 0, "max_value": 4}, "type": int} = 4, *types: Type[Content]) -> [{"name": "twitter", "type": Twitter}]:
        pass

signature_callable = _Twitter
```

Twitter:
```python
class Twitter(Platform):
        def __init__(self, auth: TwitterAuth, max_images: int = 4, *types: Type[types.Content]):
                self._twitter_auth = auth
                self.max_images = max_images
                print(f"twitter: {types}")
                super().__init__(types)
# ...

# A chain of inheritance is formed with Platform
```

And the root __init__ gets called, thus the signature is obv. incorrect and it fails.

(The first __init__ only needs a list, while we get an int for in the `Twitter` class)

![image](https://github.com/IndiePython/nodezator/assets/29675001/f9abdbe7-1e50-4fa2-a3df-a4952f501766)

For now I can make a function that calls the init correctly, but Callable mode will not work that way obv. like so:

```python
def _Twitter(auth: TwitterAuth, max_images: {"widget_name": "int_float_entry", "widget_kwargs": {"min_value": 0, "max_value": 4}, "type": int} = 4, *types: Type[Content]) -> [{"name": "twitter", "type": Twitter}]:
        return Twitter(auth, max_images, *types)

main_callable = _Twitter
```

**Comment by gregismotion** [comment]
Yup, had an old __init__ left around.

*Check your code with bigger projects!*

**Comment by KennedyRichard** [comment]
I was just about to ask for more info since I tried to replicate the problem on my end and didn't find any problems. I'm glad you pinpointed the problem.

---

Unrelated to your problem, but useful nonetheless (just a small tip): if you add the following line to your script, whenever you export a graph that contains this node the resulting Python code will import `Twitter` directly from `lazysocials.platforms`:

```python
third_party_import_text = "from lazysocials.platforms import Twitter"
```

Exporting to Python will still work fine without it, so it is not mandatory. Without it, though, the resulting exported Python code will import the `Twitter` class from your node script rather than import it directly from `lazysocials.platforms`. Functionally, the end result is the same, but it is a bit more roundabout.
