### ISSUE TITLE
Unable to delete any connection

### ISSUE THREAD

**Issue by saurabhgayali** [IndiePython/nodezator#95]
I accidently connected one node to other node that I dont intend to.
But I am unable to delete the connection.

**Comment by KennedyRichard** [comment]
Hello,

There are 02 ways to sever connections between sockets:

- Right-click one of the sockets and click the "Disconnect" options in the small popup menu that appears; or
- Hold the **<Ctrl>** key and click-drag the mouse as if you were drawing a line over the connection(s) you want to sever;

Please, try such approaches and let me know if you managed to achieve what you wanted.

**Comment by saurabhgayali** [comment]
Update: Outgoing sockets only have option to disconnect all child.
![image](https://github.com/IndiePython/nodezator/assets/13806535/c38631b7-b463-48ca-98ac-9c68e4174a20)

Only incoming sockets  have disconnect option.
![image](https://github.com/IndiePython/nodezator/assets/13806535/af4379ac-b15b-4d6b-9cc3-d4a190eea1d8)

------------
While holding and dragging invokes a selection tool.
![image](https://github.com/IndiePython/nodezator/assets/13806535/e1a22d91-936f-4bcc-bef0-0392f003a681)

**Comment by KennedyRichard** [comment]
Thank you for the report.

In the case of right-clicking the sockets, it is all expected behaviour:

- an input socket (the one that receives data) can only receive one connection, that is why it only asks whether you want to sever that connection;
- an output socket however, can send data to many sockets, which is why is asks whether you want to sever all connections;

In the case of dragging the mouse, I made a mistake in my previous reply. I'm sorry for that. I forgot to include that you must first hold the **Ctrl** key before dragging with the mouse.

Again, please, try holding **Ctrl**, then dragging the mouse and see if it works and, if so, please let me know so that I can close the issue.

Thank you again.

**Comment by saurabhgayali** [comment]
![image](https://github.com/IndiePython/nodezator/assets/13806535/2e6e8429-b83c-4542-8e31-f8823b72d453)
The ctrl method is also working.

I wonder were these steps in documentation. May be I missed. Thanks

**Comment by KennedyRichard** [comment]
Don't worry, I'm here to help whenever needed. You'll find info on the controls in the menu **Help > General controls** or pressing the **F1** key.
